"""Shared building blocks for every persistent model.

This module centralises three cross-cutting concerns so individual models stay small and
consistent:

* a deterministic constraint naming convention, which keeps database migrations stable
  and makes constraint names meaningful in error messages;
* reusable mixins for identifiers and audit timestamps;
* a factory for string-backed enumeration column types.
"""

from datetime import UTC, datetime
from enum import Enum
from uuid import UUID, uuid4

from sqlalchemy import DateTime, func
from sqlalchemy import Enum as SAEnum
from sqlmodel import Field, SQLModel

# Without an explicit convention, PostgreSQL invents constraint names. Those names differ
# between environments, which makes automatically generated migrations fragile. The
# convention below yields predictable names such as ``fk_pledges_donor_id_donors``.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# Applied to the shared metadata before any table is declared.
SQLModel.metadata.naming_convention = NAMING_CONVENTION


def utcnow() -> datetime:
    """Return the current moment as a timezone-aware UTC datetime.

    All timestamps in the system are stored in UTC and converted to local time only at
    the presentation edge, which removes an entire class of daylight-saving and
    cross-timezone defects.
    """
    return datetime.now(UTC)


def enum_column_type(enum_cls: type[Enum], name: str) -> SAEnum:
    """Build a SQLAlchemy column type that stores an enumeration as a checked string.

    Args:
        enum_cls: The Python enumeration whose *values* are persisted.
        name: Short, table-unique label used to name the CHECK constraint.

    Returns:
        A new ``Enum`` type instance. A fresh instance is returned on every call because
        constraint generation attaches state to the type object, so a single instance
        must not be shared across columns.
    """
    return SAEnum(
        enum_cls,
        name=name,
        native_enum=False,
        create_constraint=True,
        length=32,
        validate_strings=True,
        # Persist the enumeration value ("hospital_staff"), not the member name.
        values_callable=lambda members: [member.value for member in members],
    )


class UUIDPrimaryKeyMixin(SQLModel):
    """Adds a randomly generated UUID primary key named ``id``.

    UUIDs are not guessable or enumerable, so identifiers exposed in URLs do not leak
    record counts or allow scraping by incrementing a number. They can also be generated
    by the application before an insert, which simplifies building related records.
    """

    id: UUID = Field(default_factory=uuid4, primary_key=True)


class CreatedAtMixin(SQLModel):
    """Adds an immutable creation timestamp.

    The value is generated by the application and, as a safety net, defaults to the
    database clock for rows inserted outside the application (for example by a script).
    """

    created_at: datetime = Field(
        default_factory=utcnow,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )


class TimestampMixin(CreatedAtMixin):
    """Adds creation and last-modification timestamps.

    ``updated_at`` is refreshed automatically by SQLAlchemy whenever the row is updated
    through the ORM.
    """

    updated_at: datetime = Field(
        default_factory=utcnow,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now(), "onupdate": utcnow},
    )
