"""create core schema

Revision ID: 721715816b6e
Revises: 
Create Date: 2026-10-01 22:28:46.493883+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '721715816b6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_compatibility',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_group', sa.Enum('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', name='recipient_group', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('donor_group', sa.Enum('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', name='donor_group', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blood_compatibility')),
    sa.UniqueConstraint('recipient_group', 'donor_group', name='uq_blood_compatibility_recipient_donor')
    )
    op.create_index(op.f('ix_blood_compatibility_recipient_group'), 'blood_compatibility', ['recipient_group'], unique=False)
    op.create_table('component_types',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('min_interval_days_male', sa.Integer(), nullable=False),
    sa.Column('min_interval_days_female', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('min_interval_days_female > 0', name=op.f('ck_component_types_female_interval_positive')),
    sa.CheckConstraint('min_interval_days_male > 0', name=op.f('ck_component_types_male_interval_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_component_types'))
    )
    op.create_index(op.f('ix_component_types_code'), 'component_types', ['code'], unique=True)
    op.create_table('hospitals',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='verification_status', native_enum=False, create_constraint=True, length=32), server_default='pending', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_hospitals_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_hospitals_longitude_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hospitals'))
    )
    op.create_index(op.f('ix_hospitals_city'), 'hospitals', ['city'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_index(op.f('ix_hospitals_verification_status'), 'hospitals', ['verification_status'], unique=False)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('donor', 'hospital_staff', 'admin', name='user_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_users_hospital_id_hospitals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_hospital_id'), 'users', ['hospital_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity_type_entity_id', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('blood_requests',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('recipient_group', sa.Enum('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', name='recipient_group', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('component_type_id', sa.Uuid(), nullable=False),
    sa.Column('units_needed', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.Enum('critical', 'urgent', 'routine', name='urgency', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('status', sa.Enum('open', 'fulfilled', 'closed', 'expired', name='request_status', native_enum=False, create_constraint=True, length=32), server_default='open', nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('units_needed > 0', name=op.f('ck_blood_requests_units_positive')),
    sa.ForeignKeyConstraint(['component_type_id'], ['component_types.id'], name=op.f('fk_blood_requests_component_type_id_component_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_blood_requests_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_blood_requests_hospital_id_hospitals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blood_requests'))
    )
    op.create_index('ix_blood_requests_hospital_id_status', 'blood_requests', ['hospital_id', 'status'], unique=False)
    op.create_index('ix_blood_requests_status_deadline', 'blood_requests', ['status', 'deadline'], unique=False)
    op.create_table('donors',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('blood_group', sa.Enum('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', name='blood_group', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sex', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_donation_date', sa.Date(), nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('consent_to_contact', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_donors_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_donors_longitude_range')),
    sa.CheckConstraint('weight_kg > 0', name=op.f('ck_donors_weight_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_donors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donors'))
    )
    op.create_index('ix_donors_blood_group_is_available', 'donors', ['blood_group', 'is_available'], unique=False)
    op.create_index(op.f('ix_donors_user_id'), 'donors', ['user_id'], unique=True)
    op.create_table('donor_deferrals',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('donor_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('deferred_until', sa.Date(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], name=op.f('fk_donor_deferrals_donor_id_donors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_donor_deferrals_recorded_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donor_deferrals'))
    )
    op.create_index(op.f('ix_donor_deferrals_donor_id'), 'donor_deferrals', ['donor_id'], unique=False)
    op.create_table('notifications',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('donor_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'whatsapp', 'voice', name='notification_channel', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', name='notification_status', native_enum=False, create_constraint=True, length=32), server_default='queued', nullable=False),
    sa.Column('provider_message_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], name=op.f('fk_notifications_donor_id_donors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['blood_requests.id'], name=op.f('fk_notifications_request_id_blood_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('request_id', 'donor_id', 'channel', name='uq_notifications_request_donor_channel')
    )
    op.create_index(op.f('ix_notifications_donor_id'), 'notifications', ['donor_id'], unique=False)
    op.create_index(op.f('ix_notifications_request_id'), 'notifications', ['request_id'], unique=False)
    op.create_table('pledges',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('donor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pledged', 'donated', 'no_show', 'cancelled', name='pledge_status', native_enum=False, create_constraint=True, length=32), server_default='pledged', nullable=False),
    sa.Column('pledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], name=op.f('fk_pledges_donor_id_donors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['blood_requests.id'], name=op.f('fk_pledges_request_id_blood_requests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_pledges_resolved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pledges')),
    sa.UniqueConstraint('request_id', 'donor_id', name='uq_pledges_request_id_donor_id')
    )
    op.create_index(op.f('ix_pledges_donor_id'), 'pledges', ['donor_id'], unique=False)
    op.create_index('ix_pledges_request_id_status', 'pledges', ['request_id', 'status'], unique=False)
    op.create_table('donations',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pledge_id', sa.Uuid(), nullable=False),
    sa.Column('donor_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('component_type_id', sa.Uuid(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('donated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=False),
    sa.CheckConstraint('units > 0', name=op.f('ck_donations_units_positive')),
    sa.ForeignKeyConstraint(['component_type_id'], ['component_types.id'], name=op.f('fk_donations_component_type_id_component_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_donations_confirmed_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], name=op.f('fk_donations_donor_id_donors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_donations_hospital_id_hospitals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pledge_id'], ['pledges.id'], name=op.f('fk_donations_pledge_id_pledges'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donations')),
    sa.UniqueConstraint('pledge_id', name=op.f('uq_donations_pledge_id'))
    )
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donations_hospital_id'), 'donations', ['hospital_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_hospital_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index('ix_pledges_request_id_status', table_name='pledges')
    op.drop_index(op.f('ix_pledges_donor_id'), table_name='pledges')
    op.drop_table('pledges')
    op.drop_index(op.f('ix_notifications_request_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_donor_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_donor_deferrals_donor_id'), table_name='donor_deferrals')
    op.drop_table('donor_deferrals')
    op.drop_index(op.f('ix_donors_user_id'), table_name='donors')
    op.drop_index('ix_donors_blood_group_is_available', table_name='donors')
    op.drop_table('donors')
    op.drop_index('ix_blood_requests_status_deadline', table_name='blood_requests')
    op.drop_index('ix_blood_requests_hospital_id_status', table_name='blood_requests')
    op.drop_table('blood_requests')
    op.drop_index('ix_audit_log_entity_type_entity_id', table_name='audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_hospital_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hospitals_verification_status'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_city'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_component_types_code'), table_name='component_types')
    op.drop_table('component_types')
    op.drop_index(op.f('ix_blood_compatibility_recipient_group'), table_name='blood_compatibility')
    op.drop_table('blood_compatibility')
    # ### end Alembic commands ###
